[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040"
rustflags = ["--cfg", "portable_atomic_no_outline_atomics"]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[profile.dev]
debug = 2

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
debug = 1

[unstable]
build-std = ["core", "alloc"]
