[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor --flash-mode dio --flash-size 8mb"
[build]

rustflags = [
  "-C",
  "link-arg=-Wl,-Tlinkall.x",
  # Required for WiFi
  "-C",
  "link-arg=-Trom_functions.x",
  "-C",
  "link-arg=-nostartfiles",
  "-C",
  "link-arg=-Tdefmt.x",
]
target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]

[env]
ESP_LOGLEVEL = "INFO"
DEFMT_LOG = "debug"

[profile.dev]
debug = 2

[profile.dev.package."*"]
opt-level = "z"

[profile.release]
debug = 1
