[package]
edition = "2021"
name    = "tiny-ros2-codec"
version = "0.1.0"

[dependencies]
bitreader = {version = "0.3.8", default-features = false}
bytes     = {version = "1.5.0", default-features = false}
num_enum  = {version = "0.7.0", default-features = false}
